MultVAE:
  Netflix:
    batch_size: 500
    max_epochs: 100
    learning_rate: 1.0e-4
    seed: 42
    dim_bottleneck_layer: 200
    dim_hidden_layer: 600
    max_beta: 0.2
    anneal_steps: 200000
    dropout: 0.5
    stopping_criterion: "ndcg"
    stop_early: false
    save_best_to_file: true
    keep_last: false
    min_improvement: 0.0
    validation_sample_size: 10000
  MSD:
    batch_size: 500
    max_epochs: 100
    learning_rate: 1.0e-4
    seed: 42
    dim_bottleneck_layer: 200
    dim_hidden_layer: 600
    max_beta: 0.2
    anneal_steps: 200000
    dropout: 0.5
    stopping_criterion: "ndcg"
    stop_early: false
    save_best_to_file: true
    keep_last: false
    min_improvement: 0.0
    validation_sample_size: 10000
  MovieLens:
    batch_size: 500
    max_epochs: 200
    learning_rate: 1.0e-4
    seed: 42
    dim_bottleneck_layer: 200
    dim_hidden_layer: 600
    max_beta: 0.2
    anneal_steps: 200000
    dropout: 0.5
    stopping_criterion: "ndcg"
    stop_early: false
    save_best_to_file: true
    keep_last: false
    min_improvement: 0.0
    validation_sample_size: 10000
  Dummy:
    batch_size: 500
    max_epochs: 100
    learning_rate: 1.0e-4
    seed: 42
    dim_bottleneck_layer: 200
    dim_hidden_layer: 600
    max_beta: 0.2
    anneal_steps: 200000
    dropout: 0.5
    stopping_criterion: "ndcg"
    stop_early: false
    save_best_to_file: true
    keep_last: false
    min_improvement: 0.0
    validation_sample_size: 10

RecVAE:
  Netflix:
    batch_size: 500
    max_epochs: 50
    learning_rate: 5.0e-4
    n_enc_epochs: 3
    n_dec_epochs: 1
    seed: 42
    dim_bottleneck_layer: 200
    dim_hidden_layer: 600
    gamma: 0.0035
    dropout: 0.5
    stopping_criterion: "ndcg"
    stop_early: false
    save_best_to_file: true
    keep_last: false
    min_improvement: 0.0
    validation_sample_size: 10000
  MSD:
    batch_size: 500
    max_epochs: 100
    learning_rate: 5.0e-4
    n_enc_epochs: 3
    n_dec_epochs: 1
    seed: 42
    dim_bottleneck_layer: 200
    dim_hidden_layer: 600
    gamma: 0.01
    dropout: 0.5
    stopping_criterion: "ndcg"
    stop_early: false
    save_best_to_file: true
    keep_last: false
    min_improvement: 0.0
    validation_sample_size: 10000
  MovieLens:
    batch_size: 500
    max_epochs: 50
    learning_rate: 5.0e-4
    n_enc_epochs: 3
    n_dec_epochs: 1
    seed: 42
    dim_bottleneck_layer: 200
    dim_hidden_layer: 600
    gamma: 0.005
    dropout: 0.5
    stopping_criterion: "ndcg"
    stop_early: false
    save_best_to_file: true
    keep_last: false
    min_improvement: 0.0
    validation_sample_size: 10000
  Dummy:
    batch_size: 500
    max_epochs: 100
    learning_rate: 5.0e-4
    n_enc_epochs: 3
    n_dec_epochs: 1
    seed: 42
    dim_bottleneck_layer: 200
    dim_hidden_layer: 600
    gamma: 0.0035
    dropout: 0.5
    stopping_criterion: "ndcg"
    stop_early: false
    save_best_to_file: true
    keep_last: false
    min_improvement: 0.0
    validation_sample_size: 10

EASE:
  Netflix:
    l2: 2400
    alpha: 0
    density: 0.003
  MSD:
    l2: 100
    alpha: 0
    density: 0.003
  MovieLens:
    l2: 1400
    alpha: 0
    density: 0.003
  Dummy:
    l2: 250
    alpha: 0
    density: 0.003

ItemKNN:
  Netflix:
    K: 50
    normalize_X: true
    normalize_sim: true
    similarity: "cosine"
  MSD:
    K: 100
    normalize_X: true
    normalize_sim: true
    similarity: "cosine"
  MovieLens:
    K: 600
    normalize_X: true
    normalize_sim: true
    similarity: "cosine"